AY2223S2-CS2103T-T12-1/tp

src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/RemarkCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/Remark.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/PersonListCard.fxml
src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Followed tutorial for adding remark command.

Add remark command

---

docs/index.md

Minor change to update the CI badge and remove the codecov badge for AB3

Update the CI badge for index.md

---

docs/AboutUs.md
docs/team/lukkesreysandeur.md

This adds lukkesreysandeur PPP and about us.

Add lukkesreysandeur PPP and about us.

---

docs/DeveloperGuide.md

Updated DeveloperGuide.md with use cases with high priority and glossary.

Updated use cases and glossary

---

build.gradle
src/main/java/seedu/patientist/MainApp.java
src/main/java/seedu/patientist/model/Patientist.java
src/main/java/seedu/patientist/model/person/patient/Patient.java
src/main/java/seedu/patientist/model/person/patient/PatientIdNumber.java
src/main/java/seedu/patientist/model/person/patient/PatientStatusDetails.java
src/main/java/seedu/patientist/model/person/staff/Staff.java
src/main/java/seedu/patientist/model/ward/Ward.java
src/test/java/seedu/patientist/logic/commands/AddCommandIntegrationTest.java
src/test/java/seedu/patientist/logic/commands/ClearCommandTest.java
src/test/java/seedu/patientist/logic/commands/DeleteCommandTest.java
src/test/java/seedu/patientist/logic/commands/EditCommandTest.java
src/test/java/seedu/patientist/logic/commands/FindCommandTest.java
src/test/java/seedu/patientist/logic/commands/ListCommandTest.java
src/test/java/seedu/patientist/model/PatientistTest.java
src/test/java/seedu/patientist/model/person/patient/PatientIdNumberTest.java
src/test/java/seedu/patientist/model/person/patient/PatientTest.java
src/test/java/seedu/patientist/storage/JsonPatientistStorageTest.java
src/test/java/seedu/patientist/storage/JsonSerializablePatientistTest.java
src/test/java/seedu/patientist/storage/StorageManagerTest.java
src/test/java/seedu/patientist/testutil/PatientBuilder.java
src/test/java/seedu/patientist/testutil/PersonBuilder.java
src/test/java/seedu/patientist/testutil/TypicalPatients.java
src/test/java/seedu/patientist/testutil/TypicalPersons.java

This is a work in progress. Please comment if you notice any issues with code.
**Please DO NOT merge this.** I will merge this myself when ready. 
_Reviews that approve merging are still welcome, just do not click the merge button_.
currently fixes #61 #37
will be addressing #62 #42 #39

Implements Patient class + ID number + Status details, and tests

---

src/main/java/seedu/patientist/ui/HelpWindow.java

Update help to show correct UG.

---

src/main/java/seedu/patientist/MainApp.java
src/main/java/seedu/patientist/logic/commands/AddCommand.java
src/main/java/seedu/patientist/logic/parser/AddCommandParser.java
src/main/java/seedu/patientist/logic/parser/CliSyntax.java
src/main/java/seedu/patientist/logic/parser/ParserUtil.java
src/main/java/seedu/patientist/model/person/patient/Patient.java
src/main/java/seedu/patientist/model/person/patient/PatientIdNumber.java
src/main/java/seedu/patientist/model/util/SampleDataUtil.java
src/main/java/seedu/patientist/storage/JsonAdaptedPerson.java
src/main/java/seedu/patientist/ui/PersonCard.java
src/main/resources/view/PersonListCard.fxml
src/test/data/JsonSerializablePatientistTest/duplicatePatientPatientist.json
src/test/data/JsonSerializablePatientistTest/invalidPatientPatientist.json
src/test/data/JsonSerializablePatientistTest/typicalPatientPatientist.json
src/test/java/seedu/patientist/logic/LogicManagerTest.java
src/test/java/seedu/patientist/logic/commands/AddCommandIntegrationTest.java
src/test/java/seedu/patientist/logic/commands/AddCommandTest.java
src/test/java/seedu/patientist/logic/commands/CommandTestUtil.java
src/test/java/seedu/patientist/logic/parser/AddCommandParserTest.java
src/test/java/seedu/patientist/logic/parser/PatientistParserTest.java
src/test/java/seedu/patientist/model/person/patient/PatientTest.java
src/test/java/seedu/patientist/storage/JsonAdaptedPersonTest.java
src/test/java/seedu/patientist/storage/JsonPatientistStorageTest.java
src/test/java/seedu/patientist/storage/JsonSerializablePatientistTest.java
src/test/java/seedu/patientist/storage/StorageManagerTest.java
src/test/java/seedu/patientist/testutil/PatientBuilder.java
src/test/java/seedu/patientist/testutil/PatientUtil.java
src/test/java/seedu/patientist/testutil/TypicalPatients.java

Updated Parser to understand PID.
Updated AddCommand to add Patients.
Updated UI to display PID.
Updated Storage to understand PID.
Original delete still on patients no need to update.
This will close #14 if merged

Update AddCommand to add Patients

---

src/main/java/seedu/patientist/logic/commands/ListPatientsCommand.java
src/main/java/seedu/patientist/logic/parser/PatientistParser.java
src/main/java/seedu/patientist/model/Model.java
src/main/java/seedu/patientist/model/person/IsPatientPredicate.java
src/test/java/seedu/patientist/logic/commands/ListPatientCommandTest.java
src/test/java/seedu/patientist/testutil/TypicalPatients.java

List all persons objects with the "Patient" Tag.
This resolves #21

Add lspat command.

---

src/main/java/seedu/patientist/storage/JsonAdaptedPerson.java
src/test/java/seedu/patientist/storage/JsonAdaptedPersonTest.java

Fix status not saving bug

---

src/main/java/seedu/patientist/logic/commands/ListStaffCommand.java
src/main/java/seedu/patientist/logic/parser/PatientistParser.java
src/main/java/seedu/patientist/model/person/staff/IsStaffPredicate.java
src/test/java/seedu/patientist/logic/commands/ListPatientCommandTest.java
src/test/java/seedu/patientist/logic/commands/ListStaffCommandTest.java
src/test/java/seedu/patientist/testutil/TypicalStaff.java

Add lsstf command.

---

src/main/java/seedu/patientist/logic/commands/CommandResult.java
src/main/java/seedu/patientist/logic/commands/ExitCommand.java
src/main/java/seedu/patientist/logic/commands/HelpCommand.java
src/main/java/seedu/patientist/logic/commands/ViewCommand.java
src/main/java/seedu/patientist/logic/parser/CliSyntax.java
src/main/java/seedu/patientist/logic/parser/PatientistParser.java
src/main/java/seedu/patientist/logic/parser/ViewCommandParser.java
src/main/java/seedu/patientist/model/person/Person.java
src/main/java/seedu/patientist/ui/DetailsPopup.java
src/main/java/seedu/patientist/ui/MainWindow.java
src/main/resources/view/DetailsPopup.fxml
src/test/java/seedu/patientist/logic/commands/CommandResultTest.java
src/test/java/seedu/patientist/logic/commands/ExitCommandTest.java
src/test/java/seedu/patientist/logic/commands/HelpCommandTest.java

This continues from the work done by @jinnieshin at #75 . This will resolve #40

Update View Command to view by index

---

src/main/java/seedu/patientist/logic/commands/CommandResult.java
src/main/java/seedu/patientist/logic/commands/ExitCommand.java
src/main/java/seedu/patientist/logic/commands/FindCommand.java
src/main/java/seedu/patientist/logic/commands/HelpCommand.java
src/main/java/seedu/patientist/logic/commands/ViewCommand.java
src/main/java/seedu/patientist/logic/parser/PatientistParser.java
src/main/java/seedu/patientist/logic/parser/ViewCommandParser.java
src/main/java/seedu/patientist/model/person/Person.java
src/main/java/seedu/patientist/ui/DetailsPopup.java
src/main/java/seedu/patientist/ui/MainWindow.java
src/test/java/seedu/patientist/logic/commands/CommandResultTest.java
src/test/java/seedu/patientist/logic/commands/ExitCommandTest.java
src/test/java/seedu/patientist/logic/commands/HelpCommandTest.java

Added a pop up stage to show resulting details when a find command is executed.
Need to change the details shown to details of patients and staffs instead of the sample data given in AB3.
Need to design a UI for the pop up stage.

Adds a pop up stage for find command

---

src/main/java/seedu/patientist/model/Model.java
src/main/java/seedu/patientist/model/Patientist.java
src/main/java/seedu/patientist/model/person/IdNumber.java
src/main/java/seedu/patientist/model/person/Person.java
src/main/java/seedu/patientist/model/person/patient/Patient.java
src/main/java/seedu/patientist/model/person/staff/Staff.java
src/main/java/seedu/patientist/model/util/SampleDataUtil.java
src/main/java/seedu/patientist/model/ward/Ward.java
src/test/java/seedu/patientist/logic/commands/AddCommandIntegrationTest.java
src/test/java/seedu/patientist/logic/commands/FindPatientCommandTest.java
src/test/java/seedu/patientist/logic/commands/ListPatientCommandTest.java
src/test/java/seedu/patientist/logic/commands/ListStaffCommandTest.java
src/test/java/seedu/patientist/logic/commands/ListWardPatientCommandTest.java
src/test/java/seedu/patientist/model/person/AddressTest.java
src/test/java/seedu/patientist/model/person/IdNumberTest.java
src/test/java/seedu/patientist/model/person/NameContainsKeywordsPredicateTest.java
src/test/java/seedu/patientist/model/person/UniquePersonListTest.java
src/test/java/seedu/patientist/model/person/patient/IsPatientPredicateTest.java
src/test/java/seedu/patientist/model/person/patient/PatientTest.java
src/test/java/seedu/patientist/model/person/staff/IsStaffPredicateTest.java
src/test/java/seedu/patientist/model/person/staff/StaffTest.java
src/test/java/seedu/patientist/storage/JsonPatientistStorageTest.java
src/test/java/seedu/patientist/storage/JsonSerializablePatientistTest.java
src/test/java/seedu/patientist/storage/StorageManagerTest.java
src/test/java/seedu/patientist/testutil/StaffBuilder.java
src/test/java/seedu/patientist/testutil/TypicalPatients.java
src/test/java/seedu/patientist/testutil/TypicalStaff.java
src/test/java/seedu/patientist/testutil/TypicalWards.java
src/test/java/seedu/patientist/testutil/WardBuilder.java

Finalizing and debugging the functionality of Model. Refer to diff and commits for details.

Implementation and testing of Model

---

src/main/java/seedu/patientist/model/ward/Ward.java
src/main/java/seedu/patientist/model/ward/WardList.java
src/main/java/seedu/patientist/model/ward/exceptions/DuplicateWardException.java
src/main/java/seedu/patientist/model/ward/exceptions/WardNotFoundException.java
src/test/java/seedu/patientist/model/PatientistTest.java
src/test/java/seedu/patientist/model/tag/RoleTagTest.java
src/test/java/seedu/patientist/model/tag/TagTest.java
src/test/java/seedu/patientist/model/ward/WardListTest.java
src/test/java/seedu/patientist/model/ward/WardTest.java
src/test/java/seedu/patientist/testutil/WardBuilder.java

This commit also makes improvements to testing utilities related to Model, and implements Ward related exceptions

Implement testing for RoleTag and Ward

---

build.gradle
src/main/java/seedu/patientist/Main.java

Tutorial/project requirement for week 10

Enable Java assertions in build.gradle

---

src/main/java/seedu/patientist/logic/commands/CommandResult.java
src/main/java/seedu/patientist/logic/commands/ExitCommand.java
src/main/java/seedu/patientist/logic/commands/HelpCommand.java
src/main/java/seedu/patientist/logic/commands/ListWardsCommand.java
src/main/java/seedu/patientist/logic/commands/ViewCommand.java
src/main/java/seedu/patientist/logic/parser/PatientistParser.java
src/main/java/seedu/patientist/ui/MainWindow.java
src/main/java/seedu/patientist/ui/WardCard.java
src/main/java/seedu/patientist/ui/WardListPanel.java
src/main/resources/view/WardListCard.fxml
src/main/resources/view/WardListPanel.fxml
src/test/java/seedu/patientist/logic/commands/CommandResultTest.java
src/test/java/seedu/patientist/logic/commands/ExitCommandTest.java
src/test/java/seedu/patientist/logic/commands/HelpCommandTest.java
src/test/java/seedu/patientist/logic/commands/ViewCommandTest.java

This replaces the personslist column with a list of wards when lsward is used. Any other command replaces it with personlist. Still a little buggy. Patient count and Staff count does not update immediately.
This resolves #32

Add lsward command

---

src/main/java/seedu/patientist/logic/commands/AddPatientCommand.java
src/main/java/seedu/patientist/logic/commands/EditCommand.java
src/main/java/seedu/patientist/logic/parser/AddPatientCommandParser.java
src/main/java/seedu/patientist/logic/parser/CliSyntax.java
src/main/java/seedu/patientist/logic/parser/ParserUtil.java
src/main/java/seedu/patientist/model/person/patient/Patient.java
src/main/java/seedu/patientist/model/tag/PriorityTag.java
src/main/java/seedu/patientist/model/tag/RoleTag.java
src/test/java/seedu/patientist/logic/LogicManagerTest.java
src/test/java/seedu/patientist/logic/commands/CommandTestUtil.java
src/test/java/seedu/patientist/logic/parser/AddPatientCommandParserTest.java
src/test/java/seedu/patientist/logic/parser/PatientistParserTest.java
src/test/java/seedu/patientist/testutil/PatientBuilder.java
src/test/java/seedu/patientist/testutil/PatientUtil.java

Adds Priority Tag when creating new Patient.
Can edit Priority Tag using edit command.
Did not have enough time to find bugs that cause it to fail some of the tests in LogicManagerTest, PatientistParserTest, and AddPatientCommandParserTest today. Will try to fix it ASAP.
May modify it to make the priority tag optional, with the default tag being "LOW".

Implement Priority Tag for patient

---

docs/UserGuide.md

Adds Table of Contents with hyperlinks
Updates Command summary to match the current features Adds FAQ

Update Table of contents and Command summary for UG

---

src/main/java/seedu/patientist/logic/commands/AddPatientCommand.java
src/main/java/seedu/patientist/logic/parser/AddPatientCommandParser.java

bad arguments to priority tag now fail visibly, with meaningful prompt

---

docs/AboutUs.md
docs/index.md
docs/team/euph00.md

and various other changes to index/aboutus etc

Update PPP for Lin Chieh

---

src/main/java/seedu/patientist/model/person/patient/Patient.java
src/main/java/seedu/patientist/ui/DetailsPopup.java
src/main/resources/view/DetailsPopup.fxml

Fixes #169 Patient details in the output box has "details" field whereas it is called "status" in the GUI
and #181 Status and todo field for staff

Fix bugs found in mock PE

---

docs/AboutUs.md
docs/team/lukkesreysandeur.md

Add Lucas' PPP
